apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: mongodb
  name: mongodb
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: mongodb
    spec:
      containers:
      - image: {{ required "Missing value MONGODB_IMAGE" .Values.MONGODB_IMAGE }}
        imagePullPolicy: Always
        name: mongodb
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: {{ required "Missing value RREG_MONGODB_MEMORY" .Values.RREG_MONGODB_MEMORY | quote }}
        volumeMounts:
        - mountPath: /data/db/
          name: mongodb-claim0
      restartPolicy: Always
      volumes:
      - name: mongodb-claim0
        persistentVolumeClaim:
          claimName: mongodb-claim0
status: {}
