apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: regnskapsregister-api
  name: regnskapsregister-api
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: regnskapsregister-api
    spec:
      containers:
      - name: regnskapsregister-api
        image: {{ required "Missing value REGNSKAPSREGISTER-API_IMAGE" .Values.REGNSKAPSREGISTER-API_IMAGE | quote }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value RREG_REGNSKAPSREGISTER-API_MEMORY" .Values.RREG_REGNSKAPSREGISTER-API_MEMORY | quote }}
      restartPolicy: Always
status: {}
